name: GetId

main: org.powernukkit.plugins.getid.GetIdPlugin

version: "1.0.0"

api: ["1.0.11"]

author: joserobjr

description: Simple plugin that shows the ID of a block using the /getid command

website: https://github.com/PowerNukkit/getid-plugin

commands:
  getid:
    description: Shows the ID of an item or block by it's name

    usage: "/getid light_block"
    
    permission: getid.cmd.use
    
permissions:
  getid.cmd.use:
    description: "Allows the user to run the getid command"
    default: true
